### ISSUE TITLE
Strange display issue with latest upgrade to 1.16.0 that looks like maybe it also affects clean theme?

### ISSUE THREAD

**Issue by WizWareTech** [cuzy-app/clean-theme#19]
Since upgrade to 1.16.0 and clean theme 1.8.1, here is behavior of showing lists in wiki:
![image](https://github.com/cuzy-app/clean-theme/assets/13114/249bf5ad-7305-46f9-ae29-c967caa13ee8)

But if I turn this off in dev mode, it shows fine:
![image](https://github.com/cuzy-app/clean-theme/assets/13114/aeece3e9-e225-4f3f-923e-37bbf65c36f4)

How can I fix this so it always lets lists display correctly? Can you tell what caused this to start reacting like this?

Related issue: https://github.com/humhub/wiki/issues/335

**Comment by marc-farre** [comment]
@WizWareTech Thanks for reporting.
Since the Clean Theme is based on the Community theme, fixing issue https://github.com/humhub/wiki/issues/335 will fix it on the Clean Theme too.
However, I keep this issue open, because once solved on the Community Theme, we might have to rebuild and create a new version of the Clean Theme.

**Comment by WizWareTech** [comment]
I'm glad I wasn't going crazy here. I do have a related question you may be able to answer. I was able to find the corresponding inline-block change to block in clean-theme, and the markdown.less file, however, the CSS doesn't update. If I make a manual change to markdown.less, is there something I need to do to it to get it to take effect? (compile, perhaps?) How would I do that (this would just be for testing purposes knowledge in the future). I'm hoping that the fix https://github.com/humhub/wiki/issues/335 quickly, but I'm looking for a way to 'fix' it until they do permanently.

**Comment by marc-farre** [comment]
While waiting for the issue to be resolved, you can add this CSS in "Administration" -> "Settings" -> "Advanced" -> "Statistics":

```css
<style>
  .markdown-render ol, .markdown-render ul, [data-ui-markdown] ol, [data-ui-markdown] ul, [data-ui-richtext] ol, [data-ui-richtext] ul {
    display: block;
  }
</style>
```

![image](https://github.com/cuzy-app/clean-theme/assets/23310825/e98b502d-5a4a-459c-8e7c-cedebba0aa12)

Don't forget to remove it when the fix is deployed on your HumHub instance (might be version 1.16.1 of HumHub).
